= Easy JPA Entities

== Introduction

Persistence in Java using JPA (Hibernate) using immutable entities that you don't write yourself.

Instead, create a YAML file that contains definitions for your entities and let an annotation processor generate the entity classes for your.

.Notes:
* Reason for this library: I like immutability a lot. I am aware of Immutables.js and Lombok , but these don't seem to play really well with JPA.
* The ID for the entity is generated in the Java code, and is using UUID, in the examples. Generation of the UUID is not in the generated code, you should be able to replace it with anything immutable you like.
* I could have left out the setters from an entity. But I don't think a Java Object is then really immutable.
* Using this library can only be used for relatively simple entities. From what I understand from _Effective Aggregate Design_, that is how you should do it anyway: https://www.dddcommunity.org/library/vernon_2011/
* This is *not* the same as @Immutable entities in Hibernate.

.PS:
* This is currently a _work in progress_
* The artifact is not *yet* published to any maven repository.

It should be compatible with JDK 8.

== Usage

Include the easy-jpa-entities artifact in your build. For example in Maven:

....
        <dependency>
            <groupId>com.github.gerardpi.easy-jpa-entities</groupId>
            <artifactId>easy-jpa-entities-processor</artifactId>
            <version>localbuild-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
....

Create an interface, and include a YAML file with the same name with the entity definitions.

.Example:
* *Annotated file*: `easy-jpa-entities-test/src/main/java/com/github/gerardpi/easy/jpaentities/test1/_AnAnnotatedInterface.java` (this is the file to be found by the annotations processor)
* *Definitions file*: `easy-jpa-entities-test/src/main/resources/com/github/gerardpi/easy/jpaentities/test1/_AnAnnotatedInterface.yaml` (this file contains the actual definitions)

At compile time, the Java sources are being generated.

Refer to the example code in easy-jpa-entities-test/ for details.
Tests are written using https://jgiven.org/[jgiven]. These tests generate a scenario that looks a lot like https://en.wikipedia.org/wiki/Cucumber_(software)#Gherkin_language[Gherkin]. Have a look at the builds at Travis.

== CI at travis-ci.com

https://travis-ci.com/github/GerardPi/easy-jpa-entities
